{
 "title": "Camel Pod Metrics",
 "description": "Camel Metrics dashboard",
 "tags": [ "1.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total,job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod ($pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Process Start Time",
   "type": "stat",
   "description": "Process Start Time",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=\"$pod\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Camel.",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"}) * 100) / sum(base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(base_memory_committedHeap_bytes{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Threads",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "base_thread_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "base_thread_daemon_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "base_thread_max_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Camel Exchanges / 1m",
   "type": "timeseries",
   "description": "Camel Exchanges per minute",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(application_camel_context_exchanges_completed_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Exchanges Completed / 1m"
    },
    {
     "expr": "sum(increase(application_camel_context_exchanges_failed_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Exchanges Failed / 1m"
    },
    {
     "expr": "sum(increase(application_camel_context_exchanges_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Exchanges Total / 1m"
    },
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count{pod=\"$pod\"})",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Camel Processing Time in seconds",
   "type": "timeseries",
   "description": "Camel Processing Time in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(application_camel_exchange_processing_max_seconds{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "Max Processing Time"
    },
    {
     "expr": "sum(application_camel_exchange_processing_min_seconds{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "Min Processing Time"
    },
    {
     "expr": "sum(application_camel_exchange_processing_mean_seconds{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "Mean Processing Time"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"})*100) / sum(application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Camel Failures & Redelivries",
   "type": "timeseries",
   "description": "Camel Failures & Redelivries",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(application_camel_context_externalRedeliveries_total{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "External Redeliveries"
    }
   ]
  }
 ]
}