{
 "title": "Camel Route Metrics",
 "description": "Default dashboard for Fuse",
 "tags": [ "1.0" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total,job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{job=\"$job\"},pod)"
    }
   },
   {
    "name": "routeId",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\"},routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Route ($routeId)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "routeId",
   "targets": [
    {}
   ]
  },
  {
   "title": "Exchanges per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m])"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_inflight_count{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})*100) / sum(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})"
    }
   ]
  },
  {
   "title": "Min processing time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Mean processing time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Max processing time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Exchanges per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "rate(application_camel_route_exchanges_completed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_inflight_count{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Exchanges inflight"
    }
   ]
  },
  {
   "title": "Processing time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Failures handled per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_failuresHandled_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m])"
    }
   ]
  },
  {
   "title": "External Redeliveries per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_externalRedeliveries_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m])"
    }
   ]
  }
 ]
}