apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: camel-grafana
    folders: camel-grafana
  name: grafana
spec:
  config:
    auth:
      disable_login_form: "false"
      disable_signout_menu: "false"
    auth.anonymous:
      enabled: "true"
    log:
      mode: console
    security:
      admin_password: secret
      admin_user: root
  route:
    spec:
      port:
        targetPort: grafana
      tls:
        termination: edge
      to:
        kind: Service
        name: grafana-service
        weight: 100
      wildcardPolicy: None
  version: 10.4.3