---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: camel-k-integrations-operatorgroup
  namespace: camel-k-integrations
spec:
  targetNamespaces:
  - camel-k-integrations
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-hawtio-operator
  namespace: camel-k-integrations
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: red-hat-hawtio-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace