{
 "title": "Camel Integration MicroProfile Metrics",
 "description": "Dashboard for Camel Integration metrics (MicroProfile)",
 "tags": [
  "1.0",
  "MicroProfile Metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "camel integration",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{namespace=\"$namespace\", job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the Camel Integration",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_context_uptime_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts (last 5 minutes)",
   "type": "stat",
   "description": "Number of pod restarts in the last 5 minutes",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU resources",
   "type": "stat",
   "description": "Available CPUs and CPU limits set for the Camel pod",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Available CPUs:"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=\"$pod\"}",
     "legendFormat": "CPU Limits:"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU currently being used by Camel.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "description": "Memory limits set for the pod",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM HEAP Usage",
   "type": "gauge",
   "description": "Memory HEAP currently being used by Camel.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"} * 100) / base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod restarts (last 5 minutes)",
   "type": "timeseries",
   "description": "Number of pod restarts in the last 5 minutes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "Pod restarts / 5min"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Displays the \"recent cpu usage\" for the Camel integration.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "description": "Pod memory usage by Camel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "max(container_memory_rss{pod=\"$pod\"})",
     "legendFormat": "Pod RSS"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "Memory Limits"
    },
    {
     "expr": "base_memory_committedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "JVM HEAP Committed"
    },
    {
     "expr": "base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "JVM HEAP Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "description": "JVM Memory used by Camel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "JVM Heap"
    },
    {
     "expr": "vendor_memory_usedNonHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "JVM Non Heap"
    }
   ]
  },
  {
   "title": "JVM Memory HEAP Usage",
   "type": "timeseries",
   "description": "JVM Memory HEAP used by Camel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "used"
    },
    {
     "expr": "base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Threads",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "base_thread_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "base_thread_daemon_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "base_thread_max_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "GC Events by algorithm [last 5 minutes]",
   "type": "timeseries",
   "description": "Calculates the number of GC Events that occurred over a period of 5 minutes (increase/how many more)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(base_gc_total{job=\"$job\", pod=\"$pod\"}[5m])) by (name)",
     "legendFormat": "GC {{name}} events / 5min"
    }
   ]
  },
  { "title": "Camel Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Exchanges completion rate",
   "type": "stat",
   "description": "Monitors the successful completion rate of exchanges in the Camel integration by providing the percentage of successfully completed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(application_camel_context_exchanges_completed_total{job=\"$job\", pod=\"$pod\"} * 100) / application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "stat",
   "description": "Monitors the failure rate of exchanges in a Camel integration by providing the percentage of failed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"} * 100) / application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "stat",
   "description": "Number of exchanges that are currently being processed and have not yet completed within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_context_exchanges_inflight_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min processing time (by route)",
   "type": "stat",
   "description": "Minimum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}:"
    }
   ]
  },
  {
   "title": "Min processing time evolution (by route)",
   "type": "timeseries",
   "description": "Evolution of the minimum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Exchanges per second (by type)",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges per second over a period of 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(application_camel_context_exchanges_completed_total{job=\"$job\", pod=\"$pod\"}[1m])",
     "legendFormat": "Exchanges Completed"
    },
    {
     "expr": "rate(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"}[1m])",
     "legendFormat": "Exchanges Failed"
    },
    {
     "expr": "rate(application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"}[1m])",
     "legendFormat": "Exchanges Total"
    }
   ]
  },
  {
   "title": "Mean processing time (by route)",
   "type": "stat",
   "description": "Average amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}:"
    }
   ]
  },
  {
   "title": "Mean processing time evolution (by route)",
   "type": "timeseries",
   "description": "Evolution of the average amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(routeId) (application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel Failures & Redeliveries per second",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Failures & Redeliveries per second over a period of 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"}[1m])",
     "legendFormat": "Failed exchanges"
    },
    {
     "expr": "rate(application_camel_context_failuresHandled_total{job=\"$job\", pod=\"$pod\"}[1m])",
     "legendFormat": "Handled failures"
    },
    {
     "expr": "rate(application_camel_context_externalRedeliveries_total{job=\"$job\", pod=\"$pod\"}[1m])",
     "legendFormat": "External redeliveries"
    }
   ]
  },
  {
   "title": "Max processing time (by route)",
   "type": "stat",
   "description": "Maximum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}:"
    }
   ]
  },
  {
   "title": "Max processing time evolution (by route)",
   "type": "timeseries",
   "description": "Evolution of the maximum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}