{
 "title": "Camel Integration Metrics",
 "description": "Camel Integration",
 "tags": [ "1.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Camel Integration",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total,job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Start Time",
   "type": "stat",
   "description": "Process Start Time",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{pod=\"$pod\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU resources",
   "type": "stat",
   "description": "Available CPUs and CPU limits set for the Camel pod",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Available CPUs:"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=\"$pod\"}",
     "legendFormat": "CPU Limits:"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "description": "Memory limits set for the pod",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU currently being used by Camel.",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM HEAP Usage",
   "type": "gauge",
   "description": "Memory HEAP currently being used by Camel.",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"} * 100) / base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Displays the \"recent cpu usage\" for the Camel integration.",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "base_cpu_processCpuLoad_percent{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "CPU Usage %"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Threads",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "base_thread_count{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "current"
      },
      {
       "expr": "base_thread_daemon_count{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "base_thread_max_count{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Number of GC Events [30m]",
     "type": "timeseries",
     "description": "Calculates the number of GC Events that occurred over a period of 30 minutes (increase/how many more)",
     "gridPos": { "h": 6, "w": 7, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(base_gc_total{job=\"$job\", pod=\"$pod\"}[30m])) by (name)",
       "legendFormat": "GC Events ({{name}}) / 30m"
      }
     ]
    },
    {
     "title": "Pod Memory Usage",
     "type": "timeseries",
     "description": "Pod memory usage by Camel",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=\"$pod\"}",
       "legendFormat": "Memory Requests"
      },
      {
       "expr": "max(container_memory_rss{pod=\"$pod\"})",
       "legendFormat": "Pod RSS"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\"}",
       "legendFormat": "Memory Limits"
      },
      {
       "expr": "base_memory_committedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "JVM HEAP Committed"
      },
      {
       "expr": "base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "JVM HEAP Max"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "timeseries",
     "description": "JVM Memory used by Camel",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "JVM Heap"
      },
      {
       "expr": "vendor_memory_usedNonHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "JVM Non Heap"
      }
     ]
    },
    {
     "title": "JVM Memory HEAP Usage",
     "type": "timeseries",
     "description": "JVM Memory HEAP used by Camel",
     "gridPos": { "h": 6, "w": 7, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "base_memory_committedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "base_memory_usedHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "used"
      },
      {
       "expr": "base_memory_maxHeap_bytes{job=\"$job\", pod=\"$pod\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "Camel Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Exchanges completion rate",
   "type": "stat",
   "description": "Monitors the successful completion rate of exchanges in the Camel integration by providing the percentage of successfully completed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(application_camel_context_exchanges_completed_total{job=\"$job\", pod=\"$pod\"} * 100) / application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "stat",
   "description": "Monitors the failure rate of exchanges in a Camel integration by providing the percentage of failed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"} * 100) / application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "stat",
   "description": "Number of exchanges that are currently being processed and have not yet completed within the Camel integration",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_context_exchanges_inflight_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min processing time",
   "type": "stat",
   "description": "Minimum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_exchange_processing_min_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean processing time",
   "type": "stat",
   "description": "Average amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_exchange_processing_mean_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max processing time",
   "type": "stat",
   "description": "Maximum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_exchange_processing_max_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Camel Exchanges per second [5m]",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges per second over a period of 5 minutesx",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(application_camel_context_exchanges_completed_total{job=\"$job\", pod=\"$pod\"}[5m])",
     "legendFormat": "Exchanges Completed / sec"
    },
    {
     "expr": "rate(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"}[5m])",
     "legendFormat": "Exchanges Failed / sec"
    },
    {
     "expr": "rate(application_camel_context_exchanges_total{job=\"$job\", pod=\"$pod\"}[5m])",
     "legendFormat": "Exchanges Total / sec"
    },
    {
     "expr": "application_camel_context_exchanges_inflight_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Camel Processing Time",
   "type": "timeseries",
   "description": "Amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_camel_exchange_processing_max_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Max Processing Time"
    },
    {
     "expr": "application_camel_exchange_processing_min_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Min Processing Time"
    },
    {
     "expr": "application_camel_exchange_processing_mean_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Mean Processing Time"
    }
   ]
  },
  {
   "title": "Camel Failures & Redeliveries per second [5m]",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Failures & Redeliveries per second over a period of 5 minutes",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(application_camel_context_exchanges_failed_total{job=\"$job\", pod=\"$pod\"}[5m])",
     "legendFormat": "Failed exchanges / sec"
    },
    {
     "expr": "rate(application_camel_context_failuresHandled_total{job=\"$job\", pod=\"$pod\"}[5m])",
     "legendFormat": "Handled failures / sec"
    },
    {
     "expr": "rate(application_camel_context_externalRedeliveries_total{job=\"$job\", pod=\"$pod\"}[5m])",
     "legendFormat": "External redeliveries / sec"
    }
   ]
  }
 ]
}