{
 "title": "Camel Route Metrics",
 "description": "Default dashboard for Fuse",
 "tags": [ "1.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total,job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{job=\"$job\"},pod)"
    }
   },
   {
    "name": "routeId",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\"},routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Route ($routeId)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "routeId",
   "targets": [
    {}
   ]
  },
  {
   "title": "Exchanges completion rate",
   "type": "stat",
   "description": "Monitors the successful completion rate of exchanges in the Camel route by providing the percentage of successfully completed exchanges out of the total exchanges.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(application_camel_route_exchanges_completed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})*100) / sum(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "stat",
   "description": "Number of exchanges that are currently being processed and have not yet completed within the Camel route",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(application_camel_route_exchanges_inflight_count{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "stat",
   "description": "Monitors the failure rate of exchanges in the Camel route by providing the percentage of failed exchanges out of the total exchanges.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})*100) / sum(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})"
    }
   ]
  },
  {
   "title": "Min processing time",
   "type": "stat",
   "description": "Minimum amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Mean processing time",
   "type": "stat",
   "description": "Average amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Max processing time",
   "type": "stat",
   "description": "Maximum amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Exchanges per second [5m]",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges per second over a period of 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_camel_route_exchanges_completed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m]))",
     "legendFormat": "Exchanges Completed / sec"
    },
    {
     "expr": "sum(rate(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m]))",
     "legendFormat": "Exchanges Failed / sec"
    },
    {
     "expr": "sum(rate(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m]))",
     "legendFormat": "Exchanges total / sec"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "description": "Amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Exchanged Failed per second [5m]",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges failed per second over a period of 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m]))",
     "legendFormat": "Exchanges failed / sec"
    }
   ]
  },
  {
   "title": "Failures handled per second [5m]",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges failures handled per second over a period of 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_camel_route_failuresHandled_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "External Redeliveries per second [5m]",
   "type": "timeseries",
   "description": "Calculates the average rate of external redeliveries per second over a period of 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(application_camel_route_externalRedeliveries_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m]))",
     "legendFormat": "External redeliveries / sec"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(application_camel_route_exchanges_inflight_count{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"})",
     "legendFormat": "Exchanges inflight"
    }
   ]
  }
 ]
}