{
 "title": "Camel Integration Micrometer Metrics",
 "description": "Dashboard for Camel Integration metrics (Micrometer)",
 "tags": [
  "2.0",
  "Micrometer Metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(camel_exchanges_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "camel integration",
    "query": {
     "query": "label_values(camel_exchanges_total{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(camel_exchanges_total{namespace=\"$namespace\", job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The uptime of the Camel Integration",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts (last 5 minutes)",
   "type": "stat",
   "description": "Number of pod restarts in the last 5 minutes",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU resources",
   "type": "stat",
   "description": "Available CPUs and CPU limits set for the Camel pod",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Available CPUs:"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=\"$pod\"}",
     "legendFormat": "CPU Limits:"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPU currently being used by Camel.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "description": "Memory limits set for the pod",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM HEAP Usage",
   "type": "gauge",
   "description": "Memory HEAP currently being used by Camel.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"}) * 100) / sum(jvm_memory_max_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod restarts (last 5 minutes)",
   "type": "timeseries",
   "description": "Number of pod restarts in the last 5 minutes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "Pod restarts / 5min"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Displays the \"recent cpu usage\" for the Camel integration.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "description": "Pod memory usage by Camel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "max(container_memory_rss{pod=\"$pod\"})",
     "legendFormat": "Pod RSS"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\"}",
     "legendFormat": "Memory Limits"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "JVM HEAP Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "JVM HEAP Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "description": "JVM Memory used by Camel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "JVM Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "JVM Non Heap"
    }
   ]
  },
  {
   "title": "JVM Memory HEAP Usage",
   "type": "timeseries",
   "description": "JVM Memory HEAP used by Camel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Current live threads",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "current live threads"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "daemon live threads"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "peak live threads"
    }
   ]
  },
  {
   "title": "GC Events by algorithm [last 5 minutes]",
   "type": "timeseries",
   "description": "Calculates the number of garbage collection (GC) pause events that have occurred over a period of 5 minutes (increase/how many more)",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{job=\"$job\", pod=\"$pod\"}[5m])) by (gc)",
     "legendFormat": "GC {{gc}} events / 5min"
    }
   ]
  },
  { "title": "Camel Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Exchanges completion rate",
   "type": "stat",
   "description": "Monitors the successful completion rate of exchanges in the Camel integration by providing the percentage of successfully completed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(camel_exchanges_succeeded_total{job=\"$job\", pod=\"$pod\"}) * 100) / sum(camel_exchanges_total{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "stat",
   "description": "Monitors the failure rate of exchanges in a Camel integration by providing the percentage of failed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(camel_exchanges_failed_total{job=\"$job\", pod=\"$pod\"}) * 100) / sum(camel_exchanges_total{job=\"$job\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "stat",
   "description": "Number of exchanges that are currently being processed and have not yet completed within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(camel_exchanges_inflight{job=\"$job\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean processing time (by route)",
   "type": "stat",
   "description": "Average amount of time taken to process an exchange within the Camel integration by route",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(camel_message_history_seconds_sum{job=\"$job\", pod=\"$pod\"}) by (routeId) / sum(camel_message_history_seconds_count{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}:"
    }
   ]
  },
  {
   "title": "Mean processing time evolution (by route)",
   "type": "timeseries",
   "description": "Evolution of the average amount of time taken to process an exchange within the Camel integration by route",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(camel_message_history_seconds_sum{job=\"$job\", pod=\"$pod\"}) by (routeId) / sum(camel_message_history_seconds_count{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Exchanges per second (by route)",
   "type": "timeseries",
   "description": "Calculates the average rate of all Camel Exchanges (completed and failed) per second over a period of 1 minute",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_total{job=\"$job\", pod=\"$pod\"}[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "External Redeliveries per second (by route)",
   "type": "timeseries",
   "description": "Calculates the average rate of external redeliveries (initiated by an external client, e.g. a JMS broker) per second over a period of 1 minute",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_external_redeliveries_total{job=\"$job\", pod=\"$pod\"}[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Max processing time (by route)",
   "type": "stat",
   "description": "Maximum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(camel_message_history_seconds_max{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}:"
    }
   ]
  },
  {
   "title": "Max processing time evolution (by route)",
   "type": "timeseries",
   "description": "Evolution of the maximum amount of time taken to process an exchange within the Camel integration",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(camel_message_history_seconds_max{job=\"$job\", pod=\"$pod\"}) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Camel Failures per second (by route)",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Failures per second over a period of 1 minute",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_failed_total{job=\"$job\", pod=\"$pod\"}[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Failures handled per second (by route)",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges failures handled per second over a period of 1 minute",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(camel_exchanges_failures_handled_total{job=\"$job\", pod=\"$pod\"}[1m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  }
 ]
}