{
 "title": "Camel Route MicroProfile Metrics",
 "description": "Dashboard for Camel Integration route metrics (MicroProfile)",
 "tags": [
  "1.0",
  "MicroProfile Metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "camel integration",
    "query": {
     "query": "label_values(application_camel_context_exchanges_total{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{namespace=\"$namespace\", job=\"$job\"},pod)"
    }
   },
   {
    "name": "routeId",
    "label": "route",
    "query": {
     "query": "label_values(application_camel_route_exchanges_total{namespace=\"$namespace\", job=\"$job\", pod=\"$pod\"},routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Route ($routeId)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "routeId",
   "targets": [
    {}
   ]
  },
  {
   "title": "Exchanges completion rate",
   "type": "stat",
   "description": "Monitors the successful completion rate of exchanges in the Camel route by providing the percentage of successfully completed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(application_camel_route_exchanges_completed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"} * 100) / application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Exchanges failure rate",
   "type": "stat",
   "description": "Monitors the failure rate of exchanges in the Camel route by providing the percentage of failed exchanges out of the total exchanges.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"} * 100) / application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "stat",
   "description": "Number of exchanges that are currently being processed and have not yet completed within the Camel route",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_inflight_count{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Min processing time",
   "type": "stat",
   "description": "Minimum amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Mean processing time",
   "type": "stat",
   "description": "Average amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Max processing time",
   "type": "stat",
   "description": "Maximum amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "Exchanges inflight",
   "type": "timeseries",
   "description": "Number of exchanges that are currently being processed and have not yet completed within the Camel route",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_inflight_count{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Exchanges inflight"
    }
   ]
  },
  {
   "title": "Processing time evolution",
   "type": "timeseries",
   "description": "Evolution of the amount of time taken to process the route within the Camel integration",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_camel_route_processing_max_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "application_camel_route_processing_mean_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "application_camel_route_processing_min_seconds{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Exchanges per second (by type)",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges per second over a period of 1 minute",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_completed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[1m])",
     "legendFormat": "Exchanges Completed"
    },
    {
     "expr": "rate(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[1m])",
     "legendFormat": "Exchanges Failed"
    },
    {
     "expr": "rate(application_camel_route_exchanges_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[1m])",
     "legendFormat": "Exchanges total"
    }
   ]
  },
  {
   "title": "Exchanged Failed per second",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges failed per second over a period of 1 minute",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[1m])",
     "legendFormat": "Exchanges failed"
    }
   ]
  },
  {
   "title": "Failures handled per second",
   "type": "timeseries",
   "description": "Calculates the average rate of Camel Exchanges failures handled per second over a period of 1 minute",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_failuresHandled_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[1m])",
     "legendFormat": "Handled failures"
    }
   ]
  },
  {
   "title": "External Redeliveries per second",
   "type": "timeseries",
   "description": "Calculates the average rate of external redeliveries (initiated by an external client, e.g. a JMS broker) per second over a period of 1 minute",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(application_camel_route_externalRedeliveries_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}[5m])",
     "legendFormat": "External redeliveries"
    }
   ]
  }
 ]
}