---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: observability-operatorgroup
  namespace: observability
spec:
  targetNamespaces:
  - observability
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: observability
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace