---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: camel-k-integrations-operatorgroup
  namespace: camel-k-integrations
spec:
  targetNamespaces:
  - camel-k-integrations
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: camel-k-integrations
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace