---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy-can-create-token-reviews
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: grafana-oauth-sa
    namespace: camel-k-integrations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-can-view-cluster-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: grafana-oauth-sa
    namespace: camel-k-integrations
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-proxy
stringData:
  session_secret: prv5TfQhe7mt2ZsdofgNECs2oL8wT9lESHefYOqOs0M=
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: 'true'
  name: ocp-injected-certs
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: camel-grafana
    folders: camel-grafana
  name: grafana-oauth
spec:
  client:
    preferIngress: false
  config:
    security:
      admin_password: secret
      admin_user: root
    auth:
      disable_login_form: 'false'
      disable_signout_menu: 'false'
    auth.anonymous:
      enabled: 'false'
    auth.basic:
      enabled: 'true'
    users:
      auto_assign_org: 'true'
      auto_assign_org_id: '1'
      auto_assign_org_role: Viewer
    auth.proxy:
      enable_login_token: 'true'
      enabled: 'true'
      header_name: X-Forwarded-User
      header_property: username
    log:
      mode: console
  deployment:
    spec:
      template:
        replicas: 1
        spec:
          containers:
          - args:
              - '-provider=openshift'
              - '-pass-basic-auth=false'
              - '-https-address=:8443'
              - '-http-address='
              - '-email-domain=*'
              - '-upstream=http://localhost:3000'
              - '-tls-cert=/etc/tls/private/tls.crt'
              - '-tls-key=/etc/tls/private/tls.key'
              - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
              - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
              - '-cookie-expire=24h'
              - '-openshift-service-account=grafana-oauth-sa'
              - '-openshift-ca=/etc/pki/tls/cert.pem'
              - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
              - '-openshift-ca=/etc/proxy/certs/ca-bundle.crt'
              - '-skip-auth-regex=^/metrics'
              - '-skip-auth-regex=^/api/health'
            image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9
            name: grafana-proxy
            ports:
              - containerPort: 8443
                name: proxy
                protocol: TCP
            volumeMounts:
              - mountPath: /etc/tls/private
                name: grafana-tls
              - mountPath: /etc/proxy/secrets
                name: grafana-proxy
              - mountPath: /etc/proxy/certs
                name: ocp-injected-certs
          volumes:
            - name: grafana-tls
              secret:
                secretName: grafana-tls
            - name: grafana-proxy
              secret:
                secretName: grafana-proxy
            - configMap:
                name: ocp-injected-certs
              name: ocp-injected-certs
  route:
    spec:
      port:
        targetPort: proxy
      tls:
        termination: reencrypt
      to:
        kind: Service
        name: grafana-oauth-service
        weight: 100
      wildcardPolicy: None
  service:
    metadata:
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
    spec:
      ports:
        - name: proxy
          port: 443
          protocol: TCP
          targetPort: proxy
  serviceAccount:
    metadata:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
          {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-oauth-route"}}